import { useQueries } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Download, ExternalLink } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { ExplorerGrid, ExplorerHeader } from '../components/Explorer'
import { ErrorState, LoadingState, formatNumber } from '../components/Shared'
import { useExploration } from '../context/ExplorationContext'

export function ForestExplorerPage() {
  const { state, update, query } = useExploration()
  const [manifest, final] = useQueries({ queries: [
    { queryKey: ['forest-manifest'], queryFn: api.forestManifest },
    { queryKey: ['final-validation'], queryFn: api.finalValidation },
  ] })
  if (manifest.isLoading || final.isLoading) return <LoadingState />
  if (manifest.isError || final.isError) return <ErrorState error={(manifest.error || final.error) as Error} retry={() => { manifest.refetch(); final.refetch() }} />
  const data = manifest.data!
  const tree = data.trees.find(item => item.tree_index === state.tree) ?? data.trees[0]
  const model = final.data?.models.find(item => item.model_key === state.model) ?? final.data?.models[0]
  const sklearnSelected = state.model === 'sklearn_random_forest'
  const selectedUsage = data.feature_usage.find(item => item.probe_id === state.probe) ?? data.feature_usage[0]

  return <div className="explorer-page"><ExplorerHeader title="Random Forest" description="Структура на заключените модели и реални, съкратени изгледи на 30-те fitted sklearn дървета." />
    <ExplorerGrid controls={<><label className="control-field"><span>Имплементация</span><select value={state.model} onChange={event => update({ model: event.target.value })}><option value="sklearn_random_forest">Sklearn RF</option><option value="custom_random_forest">Custom RF</option></select></label>{sklearnSelected && <><span className="control-label">Дърво 1–30</span><div className="tree-index">{data.trees.map(item => <button key={item.tree_index} className={item.tree_index === tree.tree_index ? 'active' : ''} onClick={() => update({ tree: item.tree_index })}>{item.tree_index}</button>)}</div></>}<div className="parameter-stack"><span><b>30</b> дървета</span><span><b>6</b> максимална дълбочина</span><span><b>5</b> min samples split</span><span><b>15</b> входни probes</span></div></>}
      visualization={sklearnSelected ? <><div className="tree-toolbar"><div><h2>Дърво {tree.tree_index}</h2><p>Реалното fitted дърво е съкратено до depth {tree.generated_depth}.</p></div><a className="button secondary" href={api.forestTreeUrl(tree.tree_index)} download={`sklearn-tree-${tree.tree_index}.svg`}><Download size={14} /> SVG</a></div><div className="tree-canvas"><img src={api.forestTreeUrl(tree.tree_index)} alt={`Съкратена структура на sklearn дърво ${tree.tree_index}`} /></div></> : <div className="custom-forest-state"><span className="detail-index">CUSTOM RF</span><h2>30 проверени TreeNode корена</h2><p>Структурата е достъпна в заключения пакет, но отделен графичен сериализатор не е добавен, за да не се променя custom ML кодът само за представяне.</p><div className="forest-principle"><span>15 probes</span><b>→</b><span>30 дървета</span><b>→</b><span>средна вероятност</span><b>→</b><span>праг {formatNumber(model?.threshold, 2)}</span></div></div>}
      details={<><span className="detail-index">{sklearnSelected ? `TREE ${tree.tree_index}` : 'MODEL'}</span><h2>{model?.model}</h2><dl className="compact-dl"><dt>Пълен depth</dt><dd>{sklearnSelected ? tree.full_depth : 6}</dd><dt>Възли</dt><dd>{sklearnSelected ? tree.node_count : 'Не е сериализирано'}</dd><dt>Използвани probes</dt><dd>{sklearnSelected ? tree.used_probes.length : 15}</dd><dt>Заключен праг</dt><dd>{formatNumber(model?.threshold, 2)}</dd></dl>{sklearnSelected && <><h3>Probes в пълното дърво</h3><div className="probe-token-list">{tree.used_probes.map(probe => <button key={probe} className={probe === selectedUsage?.probe_id ? 'active' : ''} onClick={() => update({ probe })}>{probe}</button>)}</div><Link className="text-action" to={`/process/lasso?${query}&probe=${selectedUsage?.probe_id}`}><ExternalLink size={13} /> Отвори в LASSO</Link></>}<p className="evidence-note">Едно дърво не определя финалната прогноза. Split употребата не е доказателство за биологична важност.</p><details className="metadata-drawer"><summary>Метаданни</summary><code>{data.model_package_identity}</code><p>{data.derivation}</p></details></>}
      table={<><div className="table-toolbar"><h2>Употреба на характеристики в sklearn forest</h2><span>30 × 15 структурна матрица</span></div><div className="forest-usage"><div className="chart-frame"><ResponsiveContainer width="100%" height={260}><BarChart data={data.feature_usage} layout="vertical"><CartesianGrid stroke="#e2e5e8" horizontal={false} /><XAxis type="number" /><YAxis type="category" dataKey="probe_id" width={105} tick={{ fontFamily: 'monospace', fontSize: 10 }} /><Tooltip /><Bar dataKey="split_count" name="Брой разделяния" fill="#2f6fed" /></BarChart></ResponsiveContainer></div><div className="usage-matrix"><div className="usage-row head"><span>Дърво</span>{data.selected_probes.map(probe => <b key={probe} title={probe}>{probe.slice(0, 4)}</b>)}</div>{data.trees.map(item => <button key={item.tree_index} className={`usage-row ${item.tree_index === tree.tree_index ? 'selected' : ''}`} onClick={() => update({ tree: item.tree_index, model: 'sklearn_random_forest' })}><span>T{item.tree_index}</span>{data.selected_probes.map(probe => <i key={probe} className={item.used_probes.includes(probe) ? 'on' : ''} />)}</button>)}</div><div className="table-scroll"><table><thead><tr><th>Probe ID</th><th>Дървета</th><th>Разделяния</th><th>Мин. depth</th><th>Среден depth</th></tr></thead><tbody>{data.feature_usage.map(item => <tr key={item.probe_id} className={item.probe_id === selectedUsage?.probe_id ? 'selected-row' : ''} onClick={() => update({ probe: item.probe_id })}><th><code>{item.probe_id}</code></th><td>{item.trees_using}/30</td><td>{item.split_count}</td><td>{item.minimum_split_depth}</td><td>{formatNumber(item.mean_split_depth, 2)}</td></tr>)}</tbody></table></div></div></>}
    /></div>
}
